using System;

namespace QueryByShape.Analyzer
{
    internal static class GeneratorTemplate
    {
        public static string Build(string query, string namespaceName, string className)
        {
            return string.Format(Output, namespaceName, className, query);
        }

        public static string Output = """
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
// #pragma warning disable CS0612, CS0618

namespace {0}
{{
    public partial class {1}
    {{
        public static string ToGraphQLQuery() => @"{2}";                 
    }}
}}
""";
    }
}
