using System;

namespace QueryByShape.Analyzer
{
    internal static class GeneratorTemplate
    {
        public static string Build(string query, string namespaceName, string className)
        {
            return string.Format(Output, DateTime.Now.ToLongTimeString(), namespaceName, className, query);
        }

        public static string Output = """
// <auto-generated/> {0}

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
// #pragma warning disable CS0612, CS0618

namespace {1}
{{
    public partial class {2}
    {{
        public static string ToGraphQLQuery() => @"{3}";                 
    }}
}}
""";
    }
}
