using System.Text;

namespace QueryByShape.Analyzer
{
    internal static class QueryTemplate
    {
        public static string Build(QueryMetadata query)
        {
            StringBuilder sb = new("""
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
// #pragma warning disable CS0612, CS0618


""");
            sb.Append("namespace ");
            sb.AppendLine(query.NamespaceName);
            sb.AppendLine("{");
            sb.Append("    public partial class ");
            sb.AppendLine(query.TypeName);
            sb.AppendLine("    {");
            sb.Append("        public static string ToGraphQLQuery() => @\"");
            
            QueryEmitter.EmitQuery(query, sb);
            
            sb.AppendLine("\";                 ");
            sb.AppendLine("    }");
            sb.Append("}");
            return sb.ToString();
        }
    }
}