name: publish
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-beta"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      working-directory: ./src/QueryByShape.GraphQLClient
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push QueryByShape.GraphQLClient.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
